snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "()"
return_type = "string"
file = "app.zip"
name = "write_to_stage_sp"
handler = "app.main"
execute_as_caller = true

[dev]
database = "SI_DB"
schema = "EXTERNAL"
warehouse = "SI_WH"
role = "SI_ROLE"
overwrite = true
